apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: [OC_PROJECT]
  name: hello-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/[OC_PROJECT]/hello-openshift:[IMAGE_TAG]
        ports:
        - containerPort: 80
